  group:
    repos: |
      aetherinox/keeweb@docker/keeweb
    files:
      - source: root/
        dest: root/
      - source: rDockerfile
        dest: Dockerfile
      - source: Dockerfile.aarch64
        dest: Dockerfile.aarch64