name: "🗺️ Roadmap"
description: Planned projects in the future to do.
title: "🗺️ Roadmap: <title>"
labels: [
  "Type ◦ Roadmap"
]
body:
  - type: input
    id: roadmap-version-target
    attributes:
      label: "Target Version"
      description: Which version are we aiming to introduce this into KeeWeb?
      placeholder: "v1.90.0"
    validations:
      required: true
