# #
#   @type           github workflow
#   @desc           run linter and build tests on repository
#   @author         Aetherinox
#   @project        KeeWeb
#   @repo           https://github.com/keeweb/keeweb
# #

name: '📦 Deploy › Tests'
run-name: '📦 Deploy › Tests'

# #
#   triggers
# #

on:
    push:
        branches:
            - 'main'
            - 'master'
            - 'develop-v?[0-9]+.[0-9]+.[0-9]+'
            - 'v?[0-9]+.[0-9]+.[0-9]+'
            - '!all-contributors/**'
    pull_request:
    workflow_dispatch:
        inputs:

            # #
            #   Name of the plugin to use when creating the release zip / exe filename
            #     e.g: keeweb-v1.0.0.zip
            # #

            PLUGIN_NAME:
                description:  "📦 Name of App"
                required:     true
                default:      'keeweb'
                type:         string


# #
#   environment variables
# #

env:
    PLUGIN_NAME:            ${{ github.event.inputs.PLUGIN_NAME || 'keeweb' }}
    CHANGELOG_MODE_COMMIT:  true
    SHOW_UNCATEGORIZED:     false
    PRERELEASE:             false
    VERSION_RC:             '1'
    FOLDER_DIST:            'dist'
    BOT_NAME_1:             EuropaServ
    BOT_NAME_DEPENDABOT:    dependabot[bot]

# #
#   jobs
# #

jobs:

    job-lint:
        name: >-
            📚 Lint
        runs-on: ubuntu-latest
        steps:

            # #
            #   Job > Lint > Checkout
            # #

            - name: '☑️ Checkout'
              id: task_lint_checkout
              uses: actions/checkout@v4

            # #
            #   Job > Lint > Setup Node
            # #

            - name: '⚙️ Setup Node'
              id: task_lint_node_setup
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            # #
            #   Job > Lint > NPM Install
            # #

            - name: '🕛 NPM › Clean Install'
              id: task_lint_npm_install
              run: |
                  npm ci

            # #
            #   Job > Lint > Run
            # #

            - name: '🕞 NPM › Lint'
              id: task_lint_npm_lint
              run: |
                  npm run lint

            # #
            #   Job > Lint > Generate Coverage
            # #

            - name: '🕘 NPM › Coverage'
              id: task_lint_npm_coverage
              if: always()
              run: |
                  npm run coverage

            # #
            #   Job > Lint > Upload Coverage to Codecov
            # #

            - name: '📝 Upload Coverage Reports › Codecov'
              id: task_lint_codecov_upload
              if: steps.task_lint_npm_coverage.outcome == 'success'
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: keeweb/keeweb